### PR TITLE
First version of the Double Station Salary-spell and fix of Half Stat…

### LINKED ISSUE #15: Spell: Double salary station
Create a spell that *until the next salary* will increase the salary gained from a station by 50%.

- Event: `spell:station:double-salary`
- Payload: `{ station }` (the station index)

This spell should broadcast `station:double-salary` with a payload of `{ station }` (the station index) to everyone in the game. 

*This broadcast might not be needed in the future.*

### PR DESCRIPTION
**Pull request by LudvigStridsberg**
…ion Salary-file

Added a file containing the spell and "required" it in the spell-index-file. The spell-file copies a lot of code from the Half station salary-spell.

I also changed the Half Station Salary-file so that it exports the right function (It didn't before).

### CODE REVIEW

File: spells/double_salary_station.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+    // Reset the station's salary on the next salary payout (ie. Tick)
+    context.onNextGameTick(() => {
+        const game = context.getGameState();
+        const stationIndex = payload.station;
+        const station = game.stations[stationIndex];
+        station.properties.salaryMultiplier = 1;
+        game.stations[stationIndex] = station;
+        context.updateGameState(game);
+        context.broadcastToGame('station:regular-salary', { station: stationIndex });
```
Comment (trumtomte) [inline spells/double_salary_station.js]: Change the event to `station:double-salary:faded`.

**Review by trumtomte — CHANGES_REQUESTED** [review]
Small change.

**Review by trumtomte — APPROVED** [review]
👍🏻
