### PR TITLE
First version: spell - unlock player #26

### LINKED ISSUE #26: Spell: Unlock player
Create a spell that unlocks a locked player.

- Event: `spell:unlock:player`
- Payload: `{ playerId }` (the player ID)

This spell should use `context.sendTo` to the player and notify them with:

- Event: `unlock:player`
- Payload: `{ playerId }`

*If the player is already unlocked the spell can fail silently (ie. do nothing).*

### PR DESCRIPTION
**Pull request by jasminejasses**
Co-Authored-By: kojala <75684413+kajsaojala@users.noreply.github.com>

### CODE REVIEW

**Comment by kajsaojala** [comment]
Vi fick inte _npm run check_ att fungera så vi gjorde denna request utan det så att Louise kunde testa köra kommandot på hennes dator. Fanns en del fel att fixa när vi väl får det att fungera hos oss!

File: spells/unlock_player.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    const game = context.getGameState();
+
+    // In this spell we'll receive the player id (from frontend) (the player to be unlocked)
+    const playerId = payload.player;
+    // We'll extract the player from state.game
+    const player = game.players[playerId];
+
+    // They tried targeting an unknown player
+    if (player === undefined) {
+        context.send('spell:unlock:player:fail', { errorCode: 2 });
```
Comment (trumtomte) [inline spells/unlock_player.js]: We haven't talked about in what way errorCodes will be used, but for now lets have them start at 0 and go up for each error checking we do. This means this errorCode (since its the first one in your function) should be `0`.

**Review by trumtomte — CHANGES_REQUESTED** [review]
Small comment. Looks good otherwise 👍🏻

File: spells/unlock_player.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
+// Unlocks a player that is targeted with a "locked spell" fx. annoy
+// Takes two params, context = object containing functions to operate on state,
+// payload = data sent from client-side ex username or player-id for the targeted player
```
Comment (trumtomte) [inline spells/unlock_player.js]: The payload should only be `playerId` (as per the description: https://github.com/VilmaNilsson/VIP2021-game/issues/26)

File: spells/unlock_player.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+function unlockPlayer(context, payload) {
+  // First we'll get the game state
+  const game = context.getGameState();
+
+  // In this spell we'll receive the player id (from frontend) (the player to be unlocked)
+  const playerId = payload.player;
```
Comment (trumtomte) [inline spells/unlock_player.js]: Since the payload is `playerId` this should be `const playerId = payload.playerId;` (https://github.com/VilmaNilsson/VIP2021-game/issues/26)

File: spells/unlock_player.js [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+  player.properties.locked = false;
+
+  // Overwrite the player once it has been modified
+  game.players[playerId] = player;
+
+  // Save our changes, game is an object we want to merge in to gameState
+  context.updateGameState(game);
+
+  // Do we want to broadcast it to all players?
+  // context.broadcastToGame('player:unlocked', { player: playerId });
```
Comment (trumtomte) [inline spells/unlock_player.js]: You want to use `context.sendTo` that only sends a message to a player by their id, as noted in the description: https://github.com/VilmaNilsson/VIP2021-game/issues/26. The function `sendTo` can be found inside the Wiki (api docs) 👍🏻

**Review by trumtomte — CHANGES_REQUESTED** [review]
Finishing touches before being done 👍🏻

File: spells/unlock_player.js (hunk 2 above)
Comment (jasminejasses) [reply spells/unlock_player.js]: done :)

**Review by trumtomte — APPROVED** [review]
👍🏻
